name: thermion_flutter_ffi
description: An FFI interface for the thermion_flutter plugin (all platforms except web).
repository: https://github.com/nmfisher/thermion_flutter/thermion_flutter
version: 0.1.0+6

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"
flutter:
  plugin:
    implements: thermion_flutter_platform_interface
    platforms:
      ios:
        dartPluginClass: ThermionFlutterFFI
      android:
        dartPluginClass: ThermionFlutterFFI
      macos:
        dartPluginClass: ThermionFlutterFFI
      windows:
        dartPluginClass: ThermionFlutterFFI
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  thermion_flutter_platform_interface: ^0.1.0+6
  thermion_dart: ^0.1.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
